# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "Net": "01_embedding.ipynb",
         "emb": "01_embedding.ipynb",
         "input": "01_embedding.ipynb",
         "model": "01_embedding.ipynb",
         "optim": "01_embedding.ipynb",
         "w": "01_embedding.ipynb",
         "emp": "01_embedding.ipynb"}

modules = ["core.py",
           "embedding.py"]

doc_url = "https://gauravadlakha1509.github.io/demo_one/"

git_url = "https://github.com/gauravadlakha1509/demo_one/tree/master/"

def custom_doc_links(name): return None
